### ISSUE TITLE
Sys::CPU.processors --> Java::JavaLang::NullPointerException () under JRuby 9.2.13.0 on Windows 10

### ISSUE THREAD

**Issue by mistergibson** [djberg96/sys-cpu#11] opened 2020-10-21 02:44 UTC
Sys::CPU.processors
Traceback (most recent call last):
       16: from org.jruby.ext.win32ole.RubyWIN32OLE$INVOKER$i$0$0$each.call(RubyWIN32OLE$INVOKER$i$0$0$each.gen)
       15: from org.jruby.ext.win32ole.RubyWIN32OLE.each(RubyWIN32OLE.java:66)
       14: from org.jruby.runtime.Block.yield(Block.java:184)
       13: from org.jruby.runtime.BlockBody.yield(BlockBody.java:108)
       12: from org.jruby.runtime.IRBlockBody.doYield(IRBlockBody.java:166)
       11: from org.jruby.runtime.MixedModeIRBlockBody.commonYieldPath(MixedModeIRBlockBody.java:137)
       10: from org.jruby.ir.interpreter.Interpreter.INTERPRET_BLOCK(Interpreter.java:116)
        9: from org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:72)
        8: from org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:316)
        7: from org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:172)
        6: from org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:200)
        5: from org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:143)
        4: from org.jruby.internal.runtime.methods.MixedModeIRMethod.INTERPRET_METHOD(MixedModeIRMethod.java:156)
        3: from org.jruby.ir.interpreter.InterpreterEngine.interpret(InterpreterEngine.java:86)
        2: from org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:83)
        1: from org.jruby.ir.instructions.BSwitchInstr.interpretAndGetNewIPC(BSwitchInstr.java:99)
Java::JavaLang::NullPointerException ()

I'm not sure at this point if it is a JRuby bug, or if it is the way you're calling win32ole. Just to be sure I also filed a bug report with the JRuby folks here: https://github.com/jruby/jruby/issues/6440

**Comment by djberg96** [comment] 2020-10-21 13:50
Yep, I see the problem, but it actually has nothing to do with Windows or WIN32OLE. It is, in fact, a bad case statement caused by this line:

`self.get_cmec(cpu.ConfigManagerErrorCode)`

If you look at the `get_cmec` code, I forgot to provide an argument to case. In C Ruby, it then evaluates the `when` clauses as expressions. In JRuby, it causes an NPE. You can see it with a simple script like this:

```
# case_test.rb
def stuff(arg = nil)
  case
  when 0
    puts "zero"
  when 1
    puts "one"
  else
    puts "oops"
  end
end

stuff
```
If you run `jruby case_test.rb`, you'll see the same error.

So congrats, together we found a core bug in JRuby. ;)

**Comment by djberg96** [comment] 2020-10-21 14:24
Fixed via https://github.com/djberg96/sys-cpu/pull/12, thanks for the report!

**Closed by djberg96** 2020-10-21 14:24 UTC
